### PR TITLE
Better Mac Compatibility

### PR DESCRIPTION
**Pull request by marzent**
This is targeted specifically towards CrossOver installs, but should work with wine64 installed on Mac as well.

### CODE REVIEW

**Comment by HereInPlainSight** [comment]
Hey there!  May I ask what the status is on this?  There's not a super rush on my end, but there's an [open issue thread](https://github.com/HereInPlainSight/gshade_installer/issues/12) about Mac compatibility.  I noticed that the github repo referenced in the first post now links to your fork.  This pull request is still listed as a Draft, so I'd have to force the merge.

Should I reference that thread to check out your repo, or should I try to merge it as-is?

**Comment by marzent** [comment]
Yeah sorry I got held up by some real life stuff and then Endwalker happened…
I put it in a draft state since the auto install is still not behaving as expected and I haven’t had the time to fix it up (though I know a lot of people who got it working with the manual option on their Macs without installing half of gnu like I did xD)

Anyways if it’s ok for you I’ll remove the broken autoinstall part and then it should probably be good to go

**Comment by HereInPlainSight** [comment]
Perfectly fine, no worries.  We're all volunteers, here.  :)

That said, that's fine.  Once you pull the draft label off, I'll merge it in and let the thread know to give it another whirl.  If there's any specific instructions you recommend people to use, or if it's just a reference to the other how-to, I can add it to the readme, but obviously actually helping people with Mac issues is a bit outside my wheelhouse.

Obviously if you get a chance to fix up the autoinstall later, I won't say no to that pull request, either.  ;)

Thanks for all your work on this!

**Comment by HereInPlainSight** [comment]
Merged -- had to fix the `$winPath` situation, and since I'm still a noob at github, tested squashing.

Not entirely sure I like it, the OCD in me likes the low commit number, but definitely not thrilled it didn't put you on the main page as a contributor given the _whole_ commit was based on your changes.  One day I will figure out the logic.

Apologies for that, but hopefully this sets things right for the Mac users who were having issues, and thank you again for all the work to get Macs running!  If there's anything you want to add to the README about Macs, like the guide (I dunno how involved you are with that, I only briefly looked at it) or what have you, feel free.

I'll do my best not to screw up another pull request if you do.

**Comment by marzent** [comment]
No worries, I should have probably rebased it for the PR, though I try to avoid rewriting history if possible…

I’ll be sure to fix up the auto install in the near future (but after savage xD)

Anyhow thanks a bunch for merging, hopefully it will make peoples lives easier on macOS 👍

**Pull request merged**
