### PR TITLE
FFXIV wineprefix install changes

### PR DESCRIPTION
**Pull request by Maia-Everett**
This pull request improves support for autodetecting FFXIV in a WINEPREFIX.
* The WINEPREFIX defaults to `~/.wine` if not set manually. In this case, we don't exit early if we don't find the game.
* If FFXIV was installed to a non-default location, the script attempts to retrieve it the Wine registry.

### CODE REVIEW

**Comment by HereInPlainSight** [comment]
Hi there!  You look miles above any experience I've got, so I apologize, I just wanted to ask something as someone who's mostly just a user playing at scripting.  I threw together a [branch](https://github.com/HereInPlainSight/gshade_installer/commit/417019787399b7af23001553eb4acb7c67023513#diff-69174bcaa838f456eafb7a3974bdd8ca0ef71403143b9e0bcd771ed924d7d478) that adapted your changes, and this is just a question so I can learn for the future.  Assuming I didn't make any obvious mistakes in my branch, is there a reason I shouldn't seek to compact code like that, and avoid duplication?

I always try to do this, but I'm not sure if I'm just spinning my wheels over something that doesn't matter.  The script already feels much bigger than I anticipated at over 800 lines, but I'm not sure I should be worrying about that like I do?

I'm happy to accept both of your pull requests, to be clear, I just want to know for the future, for my own knowledge, if I'm putting too much effort in the wrong direction, and if so, why.

Also, thank you _for_ the pull requests in the first place.  I hadn't thought about checking ~/.wine or using wine's own registry to find things.

**Comment by Maia-Everett** [comment]
I haven't tested them, but your edits look good to me at first glance! They also avoid code duplication.

One caveat, though: unlike my version, yours doesn't seem to prompt to use the dxgi method for a Wine Steam installation (like it does for native Steam). I myself have GShade set up with the dxgi method, as d3d11 interferes with the Steam overlay.

**Comment by HereInPlainSight** [comment]
Sorry -- got completely eaten for like a week (week and a half?  Geez!) there.  And I completely didn't realize I'd skipped that prompt, thanks for pointing it out!  If my branch has got less code duplication (and since you don't seem to think I'm crazy for trying so hard to avoid it), I updated that and merged the branch in to cover both requests with credit for you.  If you think both use-cases are sufficiently covered, you can close them, but if you think I'm in any way missing things, for either, please definitely point them out.  :)

**Comment by Maia-Everett** [comment]
Thanks for the merge! I've closed both pull requests.

**Pull request closed without merging**
